### ISSUE TITLE
Instructions for deploying and running.

### ISSUE THREAD

**Issue by rounakraj** [aws-samples/amazon-textract-comprehend-OCRimage-search-and-analyze#1]
Hi,

I would like to try out this example. Is there an instruction or steps which i can follow to deploy and run this example.
Pardon me if this is naive question, i am fairly new to AWS and would like to try this out.

Thanks,
Rounak

**Comment by monamo19** [comment]
Hi Rounak,
We have updated the instructions for deploying this.
Please try out and let us know your feedback.
Thanks,
Mona
